# Battery Care Guidance{#ch-battery-care .unnumbered}

**Lithium Polymer batteries have a limited lifespan and should be replaced as necessary**

## Battery Maintenance

- Aim to keep battery levels above 40\% and below 65\% when not in use.
- Avoid charging the batteries to max capacity unless you are going to fly within the next day.
- When done flying, always charge your batteries at least back up to storage level (40%).
- Remove batteries from the aircraft when stored for an extended period.
- Never over-discharge your battery.
- Fully charge and discharge the battery at least once every 3 months to maintain battery health
- Do not place loose batteries on any conductive surfaces, such as metal tables.
- Batteries must be stored in climate controlled storage when not in use.  Do not expose to excessive heat or humidity.


## Preparing for flight

- When charging batteries, ensure that the charging location is clean, uncluttered and well-ventilated.
- Do not stack chargers when charging batteries, or place batteries on the power adapter during charging.
- Do not leave batteries charging unattended.
- Do not charge batteries near flammable materials or on flammable surfaces.
- Plan to charge batteries no earlier than 3 days prior to flight.


## Immediately after flight

- Power off the aircraft completely before removing the battery.
- After removing a used battery, store the battery in a shaded, but well-ventilated location.  
- Never store a recently used and warm battery in an enclosed battery bag or UAS case. 
- Document any performance issues immediately.


## Battery Inspection

- Check battery voltage levels at least once a month when not in use.
- Check for bulging, swelling or cracks in battery casing.
- Check for signs of electrical arcing, such as burn marks or melted plastic around the battery terminals.
- Safely discard any battery that is showing any sign of damage or bulging.


## Battery Travel

- Always store batteries in a ventilated location
- Never transport a damaged battery or a battery with less than 5\% remaining
- Always store batteries in a specified transportation box/bag before the transit to avoid damage from external forces. 
- Do not store a battery with metal components such as paperclips, screws or metal nuts.


## Battery Incidents

- Do not use a battery that has been involved in a serious crash or heavy impact.
- If a battery falls into water with the aircraft during flight, take it out immediately, and place it in a safe and open area.  Maintain a safe distance from the battery until it is completely dry. Never use the battery again, and dispose of the battery properly. Do not use heat to dry batteries.  
- Put out any battery fire using sand, or a dry powder fire extinguisher.
